### PR TITLE
Prevent segfaults: defer closing until all operations are done

### LINKED ISSUE #32: Don't process close() until current in-flight async ops are complete
Will involve more tracking like the delete-iterators-on-close work. Each async operation will have to increment a counter when starting and decrement when done, will also need to trigger a possible-close function when done.
Without this, a segfault is possible when you close() while an operation is in-flight.

### PR DESCRIPTION
**Pull request by vweevers**
Closes #32. Follow-up to #597.

I made sure to replicate a segfault (or a failed LevelDB assertion in the case of `get()`) for each operation before fixing it. That required repeating the tests a few thousand times with a forloop; I didn't keep that code because it would make CI runs too long. I wasn't able to replicate a segfault for `approximateSize()` but I'm confident enough in the basic mechanism to let that slide. Lastly, `compactRange()` did not segfault either but it did hang, so that's fixed now too.

### CODE REVIEW

**Comment by vweevers** [comment]
AppVeyor failure is unrelated (temporary network issue), restarting that job.

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (C:\projects\leveldown\node_modules\node-gyp\lib\install.js:197:21)
gyp ERR! stack     at Request.emit (events.js:193:13)
gyp ERR! stack     at Request.onRequestError (C:\projects\leveldown\node_modules\request\request.js:881:8)
gyp ERR! stack     at ClientRequest.emit (events.js:193:13)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:397:9)
gyp ERR! stack     at TLSSocket.emit (events.js:193:13)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:91:8)
gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:81:17)
gyp ERR! System Windows_NT 6.3.9600
```

File: test/segfault-test.js [hunk 1]
```diff
@@ -1,28 +1,89 @@
...
+testPending('approximateSize()', 1, function (db, next) {
+  db.approximateSize('a', 'z', next)
+})
+
+testPending('compactRange()', 1, function (db, next) {
+  db.compactRange('a', 'z', next)
+})
+
+// Test multiple pending operations, using all of the above.
+testPending('operations', operations.length, function (db, next) {
```
Comment (ralphtheninja) [inline test/segfault-test.js]: Badass!
